#pragma once

#define DISPOSITION_TITLE "Save Location"

#define IDD_ICON                   1
#define IDD_ICON_PROPERTIES        2
#define IDD_ICON_SAVE_AS           3
#define IDD_ICON_LOGO              4
#define IDD_ICON_CANCEL            5
#define IDD_ICON_DOODLE            6
#define IDD_ICON_START             7
#define IDD_ICON_CREATE            8
#define IDD_ICON_HELP              9
#define IDD_ICON_ABOUT             10
#define IDD_ICON_OPEN              11
#define IDD_ICON_WEB               12
#define IDD_ICON_WEB_HOMEPAGE      13
#define IDD_ICON_WEB_TRAINING      14
#define IDD_ICON_DOODLE_II         15
#define IDD_ICON_CANCEL_DISABLED   16
#define IDD_ICON_PROPERTIES_DISABLED   17
#define IDD_ICON_FORGET            18
#define IDD_ICON_FORGET_DISABLED   19
#define IDD_ICON_UNDO              20
#define IDD_ICON_UNDO_DISABLED     21
#define IDD_ICON_SEAL              22
#define IDD_ICON_SEAL_DISABLED     23
#define IDD_ICON_REPEAT            24
#define IDD_ICON_REPEAT_DISABLED   25
#define IDD_ICON_SAVE_AS_DISABLED  26
#define IDD_ICON_DOODLE_DISABLED   27
#define IDD_ICON_QUICK_DRAW        29
#define IDD_ICON_QUICK_DRAW_WRITE  30
#define IDD_ICON_QUICK_DRAW_WRITE_DISABLED   31

#define ID_ACCELERATORS            30

#define IDBITMAP_BACKGROUND         1

#define PROPERTY_PAGE_WIDTH         360
#define PROPERTY_PAGE_HEIGHT        380

#define IDD_GLOBAL_REPOSITORY       100
#define IDD_DISPOSITION_PROPERTIES  200
#define IDD_DISPOSITION_EMAIL       300
#define IDD_PRINTER_PROFILES        400
#define IDD_BACKENDS                900
#define IDD_OPTIONS                 950
#define IDD_INHERITED_DOCUMENT      960
#define IDD_DISPOSITION_MORE        1200
#define IDD_DOODLE_OPTIONS          970
#define IDD_DISPLAY_WAITING         1300
#define IDD_REGISTRATION            1000

#define IDD_CURSIVISION_CONTROL_OPTIONS         1500
#define IDD_DOCUMENT_TEMPLATE                   1600
#define IDD_CURSIVISION_RECOGNITION             1700
#define IDD_SIGNING_LOCATIONS                   1800
#define IDD_SIGNING_LOCATIONS_ORDER             1850
#define IDD_DATA_FIELDS                         1900
#define IDD_DATA_FIELDS_LABEL                   1950

#define IDD_ABOUT                               2000

#define IDD_GLOBAL_TEMPLATE                     3000
#define IDD_GLOBAL_TEMPLATE_FIELD_PROPERTIES    3050
#define IDD_GLOBAL_TEMPLATE_FIELDS              3100
#define IDD_GLOBAL_TEMPLATE_DATE_FIELD_PROPS    3150
#define IDD_GLOBAL_TEMPLATE_PROFILE_ORDER       3160

#define IDC_EXIT                 200
#define IDC_GETFILE              300
#define IDC_SAVE_AS              301
#define IDC_REOPEN_SOURCE        302
#define IDC_FILENAME             400
#define IDC_CONTROL_HOST         500
#define IDC_UPDATE_PDF           600
#define IDC_SELECT_REGION        700
#define IDC_SELECT_TARGET        701
#define IDC_SELECT_PIECES        702
#define IDC_SELECT_PIECE_TARGETS 703
#define IDC_CLOSE_FILE           704
#define IDC_PRINT                705
#define IDC_SELECT_FONT          706

#define IDR_MAIN_MENU            100
#define IDR_PROCESS_MENU         101

#define ID_HELP_INSTRUCTIONS     150
#define ID_FILE_EXIT             160
#define ID_SIGNATURE_DEVICE      200

#define ID_CURSIVISION_ONLINE                      1303
#define ID_CURSIVISION_ONLINE_HOME                 1304
#define ID_CURSIVISION_ONLINE_TRAINING_VIDEOS      1305
#define ID_ABOUT                 1306

#define ID_DOODLE                180
#define ID_DOODLE_CANCEL         1801
#define ID_DOODLE_OPTIONS        181
#define ID_DOODLE_FORGET         182

#define ID_SETUP                 190
#define ID_DOODLE_START          191
#define ID_RESET_DOODLE_OPTIONS  192
#define ID_MANAGE_PROFILES       193

#define ID_BACKEND_EXECUTE_1     401
#define ID_BACKEND_EXECUTE_MAX   464

#define ID_BACKEND_PROPERTIES_1     501
#define ID_BACKEND_PROPERTIES_MAX   564

#define IDDI_GLOBAL_REPOSITORY      101
#define IDDI_GET_GLOBAL_REPOSITORY  102

#define IDDI_DISPOSITION_SAVE                            201
#define IDDI_DISPOSITION_SHOW_STARTUP_PROPERTIES_LABEL   202
#define IDDI_DISPOSITION_SHOW_STARTUP_PROPERTIES         203
#define IDDI_DISPOSITION_USE_LARGEST_VERTICAL_RES        204
#define IDDI_DISPOSITION_APPEND                          205
#define IDDI_DISPOSITION_APPEND_DATE                     206
#define IDDI_DISPOSITION_APPEND_TIME                     207
#define IDDI_DISPOSITION_SUFFIX                          209
#define IDDI_DISPOSITION_SUFFIX_LABEL                    210
#define IDDI_DISPOSITION_REPLACE                         211
#define IDDI_DISPOSITION_SEQUENCE                        212
#define IDDI_DISPOSITION_SAVE_IN_LABEL                   213
#define IDDI_DISPOSITION_SAVE_MY_DOCUMENTS               214
#define IDDI_DISPOSITION_SAVE_BY_ORIGINAL                215
#define IDDI_DISPOSITION_SAVE_IN                         216
#define IDDI_DISPOSITION_SAVE_LOCATION                   217
#define IDDI_DISPOSITION_CHOOSE_SAVE_LOCATION            218
#define IDDI_DISPOSITION_PRINT                           219
#define IDDI_DISPOSITION_PRINTER                         220
#define IDDI_DISPOSITION_SHOW_PROPERTIES                 228
#define IDDI_DISPOSITION_ACCEPT                          230
#define IDDI_DISPOSITION_RETAIN_SIGNED                   231
#define IDDI_DISPOSITION_REOPEN_ORIGINAL                 232
#define IDDI_DISPOSITION_CLOSE_DOCUMENT                  2325
#define IDDI_DISPOSITION_EXIT                            233
#define IDDI_DISPOSITION_OPEN_LAST_DOCUMENT              234
#define IDDI_DISPOSITION_WHILE_SIGNING_PROPERTIES_LABEL  235
#define IDDI_DISPOSITION_WHILE_SIGNING_SHOW_PAD          236
#define IDDI_DISPOSITION_EXIT_POST_LABEL                 237
#define IDDI_DISPOSITION_CONTINUOUS_DOODLE_LABEL         2385
#define IDDI_DISPOSITION_CONTINUOUS_DOODLE_LEARN         238
#define IDDI_DISPOSITION_CONTINUOUS_DOODLE_OFF           239
#define IDDI_DISPOSITION_CONTINUOUS_DOODLE_ON            240
#define IDDI_DISPOSITION_REMEMBER                        241
#define IDDI_HEADER_TEXT                                 242
#define IDDI_DO_REMEMBER_LABEL                           243
#define IDDI_DISPOSITION_NEED_ADMIN_PRIVILEGES           244
#define IDDI_NO_TEMPLATE_LABEL                           245
#define IDDI_NO_TEMPLATE_LABEL2                          246

#define IDDI_DISPOSITION_MORE                            251
#define IDDI_DISPOSITION_SAVE_MONTHYEAR                  252
#define IDDI_DISPOSITION_SAVE_DAYMONTH                   253
#define IDDI_DISPOSITION_SAVE_VALIDATION                 254

#define IDDI_INHERITED_DOCUMENT_TEXT                     961
#define IDDI_INHERITED_DOCUMENT_PROPERTIES               962

#define IDDI_SIDEBAR_NO_DOCUMENT                         300
#define IDDI_SIDEBAR_STATUS                              301
#define IDDI_SIDEBAR_NAVIGATE                            302
#define IDDI_SIDEBAR_WRITE                               303
#define IDDI_SIDEBAR_ERASE                               304

#define IDDI_SIDEBAR_BEGIN                               305
#define IDDI_SIDEBAR_PREVIOUS                            306
#define IDDI_SIDEBAR_NEXT                                307
#define IDDI_SIDEBAR_CLEAR                               308
#define IDDI_SIDEBAR_END                                 309
#define IDDI_SIDEBAR_NAVIGATE_DURING_PLAYBACK            310
#define IDDI_SIDEBAR_CONTINUE_DURING_PLAYBACK            311
#define IDDI_SIDEBAR_CANCEL                              312

#define IDDI_SIDEBAR_FINISH                              320

#define IDDI_TOPBAR_NO_DOCUMENT                          400
#define IDDI_TOPBAR_STATUS                               401
#define IDDI_TOPBAR_INSTRUCTIONS                         402
#define IDDI_TOPBAR_FORGET                               403
#define IDDI_TOPBAR_LOCATION_STATUS                      404
#define IDDI_TOPBAR_REMOVE                               405

#define IDDI_DISPOSITION_MULTI_SIGN_RIGHT_MOTION         1101
#define IDDI_DISPOSITION_MULTI_SIGN_DOWN_MOTION          1102

#define IDDI_PRINTING_PROFILES                      400
#define IDDI_PROFILE_SET_GLOBAL                     401
#define IDDI_PRINTING_PROFILE_SETTINGS              402
#define IDDI_PRINTING_PROFILE_DELETE                403
#define IDDI_PRINTING_PROFILE_USE_FILENAME          404
#define IDDI_PRINTING_INSTRUCTIONS                  405
#define IDSTR_PRINTING_INSTRUCTIONS_BUILTIN         4051
#define IDSTR_PRINTING_INSTRUCTIONS_BYNAME          4052
#define IDSTR_PRINTING_INSTRUCTIONS_GLOBAL_TEMPLATE 4053

#define IDDI_PRINTING_DEVICE_ASSOCIATE_PRC         410
#define IDDI_PRINTING_DEVICE_ASSOCIATION           411
#define IDDI_PRINTING_DEVICE_ASSOCIATION_FIND      412
#define IDDI_PRINTING_DEVICE_DOODLE_INSTRUCTIONS_1 413
#define IDDI_PRINTING_DEVICE_DOODLE_INSTRUCTIONS_2 414
#define IDDI_PRINTING_DEVICE_JUST_SIGN_LABEL       415
#define IDDI_PRINTING_DEVICE_JUST_SIGN             416
#define IDDI_PRINTING_DEVICE_MANUAL_CREATE_LABEL   417
#define IDDI_PRINTING_DEVICE_MANUAL_CREATE         418
#define IDDI_PRINTING_ALLOW_NON_ADMIN_ACCESS       419
#define IDDI_PRINTING_NO_RECOGNITION_STRATEGY      420

#define IDDI_PRINTING_ALT_RECOGNIZE_SET_GLOBAL          423
#define IDDI_PRINTING_ALT_RECOGNIZE_MANUAL_SELECT       424
#define IDDI_PRINTING_ALT_RECOGNIZE_MANUAL_SELECT_STR2  4242
#define IDDI_PRINTING_ALT_RECOGNIZE_GLOBAL_TEMPLATE     425
#define IDDI_PRINTING_ALT_RECOGNIZE_NONE                426

#define IDDI_PRINTING_ALT_RECOGNIZE_DESCRIPTION         427

#define IDDI_PRINTING_DEVICE_PROFILE_OK         620
#define IDDI_PRINTING_DEVICE_PROFILE_CANCEL     621

#define IDDI_PRINTING_VIEW_PROFILE_NAME         701
#define IDDI_PRINTING_VIEW_INSTRUCTIONS         702
#define IDDI_PRINTING_VIEW_VIEW                 703
#define IDDI_PRINTING_VIEW_REGION_DELETE        704
#define IDDI_PRINTING_VIEW_OK                   705
#define IDDI_PRINTING_VIEW_CANCEL               706
#define IDDI_PRINTING_VIEW_POINT_SELECT         707
#define IDDI_PRINTING_VIEW_DRAG_SELECT          708
#define IDDI_PRINTING_VIEW_REGIONS_RESET        709

#define IDDI_BACKENDS_ALLOW_NON_ADMIN           901
#define IDDI_BACKENDS_LIST_LABEL                902
#define IDDI_BACKENDS_LIST                      903

#define IDDI_BACKENDS_USE_BACKEND               910
#define IDDI_BACKENDS_USE_BACKEND_MAX           942
#define IDDI_BACKENDS_PROPERTIES                943
#define IDDI_BACKENDS_PROPERTIES_MAX            975
#define IDDI_BACKENDS_ORDER                     976
#define IDDI_BACKENDS_ORDER_MAX                1008

#define IDDI_BACKENDS_TOP_LIST_LABEL           1010
#define IDDI_BACKENDS_TOP_LIST                 1011
#define IDDI_BACKENDS_BOTTOM_LIST_LABEL        1012
#define IDDI_BACKENDS_BOTTOM_LIST              1013
#define IDDI_BACKENDS_MOVE_TO_TOP_LIST         1014
#define IDDI_BACKENDS_REMOVE_FROM_TOP_LIST     1015

#define IDDI_OPTIONS_TEXT                       951
#define IDDI_OPTIONS_OPTION_1                   952
#define IDDI_OPTIONS_OPTION_2                   953
#define IDDI_OPTIONS_OPTION_3                   954

#define IDDI_DOODLE_OPTIONS_LABEL1              961
#define IDDI_DOODLE_OPTIONS_LABEL2              962
#define IDDI_DOODLE_OPTIONS_LABEL3              963
#define IDDI_DOODLE_OPTIONS_LABEL4              964
#define IDDI_DOODLE_OPTIONS_LABEL5              965
#define IDDI_DOODLE_OPTIONS_REMEMBER            966
#define IDDI_DOODLE_OPTIONS_FORGET              967
#define IDDI_DOODLE_OPTIONS_OWN_DISPOSITION     968
#define IDDI_DOODLE_OPTIONS_DISPOSITION         969
#define IDDI_DOODLE_OPTIONS_RESETBUTTON         970
#define IDDI_DOODLE_OPTIONS_LEFTBUTTON          971
#define IDDI_DOODLE_OPTIONS_RIGHTBUTTON         972
#define IDDI_DOODLE_OPTIONS_ERASEBUTTON         973
#define IDDI_DOODLE_OPTIONS_DESC                974

#define IDDI_ABOUT_ICON                        1000
#define IDDI_ABOUT_SYSTEM_DESCRIPTION          1001
#define IDDI_ABOUT_VERSION_NO_DATE             1002
#define IDDI_ABOUT_SIGNATURE_PAD               1003
#define IDDI_ABOUT_THANK_YOU                   1004
#define IDDI_ABOUT_REGISTRATION_INFO           1005
#define IDDI_ABOUT_REGISTRATION_INFO_COPY      1006

#define IDDI_DISPLAY_WAITING_LABEL1            1301
#define IDDI_DISPLAY_WAITING_LABEL2            1302
#define IDDI_DISPLAY_WAITING_SHOW              1303

#define IDDI_SIGNING_LOCATIONS_LABEL1          1701
#define IDDI_SIGNING_LOCATIONS_LABEL2          1702
#define IDDI_SIGNING_LOCATIONS_LABEL3          1703
#define IDDI_SIGNING_LOCATIONS_VIEW            1710
#define IDDI_SIGNING_LOCATIONS_SCROLL          1711
#define IDDI_SIGNING_LOCATIONS_NEW             1720
#define IDDI_SIGNING_LOCATIONS_DELETE          1721
#define IDDI_SIGNING_LOCATIONS_CUT             1722
#define IDDI_SIGNING_LOCATIONS_COPY            1723
#define IDDI_SIGNING_LOCATIONS_PASTE           1724
#define IDDI_SIGNING_LOCATIONS_SET_ORDER       1725

#define IDDI_SIGNING_LOCATIONS_ORDER           1801
#define IDDI_SIGNING_LOCATIONS_ORDER_SPIN      1802
#define IDDI_SIGNING_LOCATIONS_ORDER_LABEL     1803
#define IDDI_SIGNING_LOCATIONS_ORDER_OK        1804
#define IDDI_SIGNING_LOCATIONS_ORDER_CANCEL    1805

#define IDDI_CV_CONTROL_TEMPLATE          100
#define IDDI_CV_CONTROL_TEMPLATE_GET      101
#define IDDI_CV_DOCUMENT                  102
#define IDDI_CV_DOCUMENT_SCROLL           103
#define IDDI_CV_RECOGNITION_INSTRUCTIONS  104
#define IDDI_CV_LOCATIONS_RESET           105
#define IDDI_CV_LIMIT_REACHED             106
#define IDDI_CV_LOCATIONS_INSTRUCTIONS    107
#define IDDI_CV_LOCATIONS_ADDITIONAL_INFO       108
#define IDDI_CV_LOCATIONS_FULLPAGE_INSTRUCTIONS 109
#define IDDI_CV_LOCATIONS_ALREADY_DEFINED       110
#define IDDI_CV_MORE_INFORMATION                111
#define IDDI_CV_IMAGE_RECOGNITION_INSTRUCTIONS  112

#define IDDI_DATA_FIELDS_RESET          1901
#define IDDI_DATA_FIELDS_INSTRUCTIONS   1902
#define IDDI_DATA_FIELDS_DELETE         1903
#define IDDI_DATA_FIELDS_LABEL          1904
#define IDDI_DATA_FIELDS_GENERATE       1905
#define IDDI_DATA_FIELDS_GENERATE_LABEL 1906
#define IDDI_FIELDS_LABEL_LABEL         1951
#define IDDI_FIELDS_VALUE_REQUIRED      1952
#define IDDI_FIELDS_LABEL_OK            1953
#define IDDI_FIELDS_LABEL_CANCEL        1954

#define IDDI_IMAGE_FIELDS_TYPE              1975
#define IDDI_IMAGE_FIELD_TABS               2021

#define IDDI_IMAGE_FIELD_FIELD_GB           1925

#define IDDI_IMAGE_FIELD_DESCRIPTION        1926
#define IDDI_IMAGE_FIELD_LABEL              1927
#define IDDI_IMAGE_FIELD_LABEL_LEFT         1928
#define IDDI_IMAGE_FIELD_LEFT               1929
#define IDDI_IMAGE_FIELD_LEFT_SPIN          1930
#define IDDI_IMAGE_FIELD_LABEL_BOTTOM       1931
#define IDDI_IMAGE_FIELD_BOTTOM             1932
#define IDDI_IMAGE_FIELD_BOTTOM_SPIN        1933
#define IDDI_IMAGE_FIELD_LABEL_WIDTH        1934
#define IDDI_IMAGE_FIELD_WIDTH              1935
#define IDDI_IMAGE_FIELD_WIDTH_SPIN         1936
#define IDDI_IMAGE_FIELD_LABEL_HEIGHT       1937
#define IDDI_IMAGE_FIELD_HEIGHT             1938
#define IDDI_IMAGE_FIELD_HEIGHT_SPIN        1939

#define IDDI_IMAGE_FIELD_COMP_SIG_FIELD_GB  1976

#define IDDI_IMAGE_FIELD_SIG_DESCRIPTION    1977
#define IDDI_IMAGE_FIELD_SIG_LABEL          1978
#define IDDI_IMAGE_FIELD_SIG_LABEL_RIGHT    1979
#define IDDI_IMAGE_FIELD_SIG_RIGHT          1980
#define IDDI_IMAGE_FIELD_SIG_RIGHT_SPIN     1981
#define IDDI_IMAGE_FIELD_SIG_LABEL_UP       1982
#define IDDI_IMAGE_FIELD_SIG_UP             1983
#define IDDI_IMAGE_FIELD_SIG_UP_SPIN        1984
#define IDDI_IMAGE_FIELD_SIG_LABEL_WIDTH    1985
#define IDDI_IMAGE_FIELD_SIG_WIDTH          1986
#define IDDI_IMAGE_FIELD_SIG_WIDTH_SPIN     1987
#define IDDI_IMAGE_FIELD_SIG_LABEL_HEIGHT   1988
#define IDDI_IMAGE_FIELD_SIG_HEIGHT         1989
#define IDDI_IMAGE_FIELD_SIG_HEIGHT_SPIN    1990
#define IDDI_IMAGE_FIELD_SIG_NOTIFY_LABEL   1991
#define IDDI_IMAGE_FIELD_SIG_NOTIFICATION   1992

#define IDDI_IMAGE_FIELD_COMP_DATE_FIELD_GB 2000

#define IDDI_IMAGE_FIELD_DATE_DESCRIPTION   2001
#define IDDI_IMAGE_FIELD_DATE_LABEL         2002
#define IDDI_IMAGE_FIELD_DATE_LABEL_RIGHT   2003
#define IDDI_IMAGE_FIELD_DATE_RIGHT         2004
#define IDDI_IMAGE_FIELD_DATE_RIGHT_SPIN    2005
#define IDDI_IMAGE_FIELD_DATE_LABEL_UP      2006
#define IDDI_IMAGE_FIELD_DATE_UP            2007
#define IDDI_IMAGE_FIELD_DATE_UP_SPIN       2008
#define IDDI_IMAGE_FIELD_DATE_LABEL_WIDTH   2009
#define IDDI_IMAGE_FIELD_DATE_WIDTH         2010
#define IDDI_IMAGE_FIELD_DATE_WIDTH_SPIN    2011
#define IDDI_IMAGE_FIELD_DATE_LABEL_HEIGHT  2012
#define IDDI_IMAGE_FIELD_DATE_HEIGHT        2013
#define IDDI_IMAGE_FIELD_DATE_HEIGHT_SPIN   2014

#define IDDI_IMAGE_FIELD_COMP_QUADRANT_GB   2050
#define IDDI_IMAGE_FIELD_COMP_QUADRANT_DESC 2051
#define IDDI_IMAGE_FIELD_COMP_QUADRANT      2052
#define IDDI_IMAGE_FIELD_COMP_QUADRANT_WARN     2053
#define IDDI_IMAGE_FIELD_COMP_QUADRANT_WARN2    2054
#define IDDI_IMAGE_FIELD_COMP_QUADRANT_WARN3    2055
#define IDDI_IMAGE_FIELD_COMP_QUADRANT_WARN4    2056
#define IDDI_IMAGE_FIELD_COMP_QUADRANT_WARN5    2057
#define IDDI_IMAGE_FIELD_COMP_QUADRANT_WARN6    2058

#define IDDI_REGISTRATION_CV_IMAGE       1001
#define IDDI_REGISTRATION_LABEL1         1002
#define IDDI_REGISTRATION_LABEL2         1003
#define IDDI_REGISTRATION_LABEL3         1004
#define IDDI_REGISTRATION_LABEL4         1005
#define IDDI_REGISTRATION_LABEL5         1006
#define IDDI_REGISTRATION_LABEL6         1007
#define IDDI_REGISTRATION_LABEL7         1008
#define IDDI_REGISTRATION_CONTACT        1021
#define IDDI_REGISTRATION_ORGANIZATION   1022
#define IDDI_REGISTRATION_PHONE          1023
#define IDDI_REGISTRATION_EMAIL          1024
#define IDDI_REGISTRATION_RESET          1030
#define IDDI_REGISTRATION_INFO           1040
#define IDDI_REGISTRATION_INFO_OTHER_MACHINE    1041

#define IDDI_GLOBAL_TEMPLATE_DOCUMENT_NON_ADMIN     3001
#define IDDI_GLOBAL_TEMPLATE_DOCUMENT               3002
#define IDDI_GLOBAL_TEMPLATE_DOCUMENT_GET           3003
#define IDDI_GLOBAL_TEMPLATE_DOCUMENT_GET_WARN      3004
#define IDDI_GLOBAL_TEMPLATE_PROFILES_LABEL         3005
#define IDDI_GLOBAL_TEMPLATE_PROFILES               3006
#define IDDI_GLOBAL_TEMPLATE_PROFILE_ADD            3007
#define IDDI_GLOBAL_TEMPLATE_PROFILE_REMOVE         3008
#define IDDI_GLOBAL_TEMPLATE_SETTINGS               3009
#define IDDI_GLOBAL_TEMPLATE_ORDER                  3010

#define IDDI_GLOBAL_TEMPLATE_MORE_DOCUMENTS         3011
#define IDDI_GLOBAL_TEMPLATE_MORE_ADD               3012
#define IDDI_GLOBAL_TEMPLATE_MORE_REMOVE            3013
#define IDDI_GLOBAL_TEMPLATE_FIELDS_SHOW            3014
#define IDDI_GLOBAL_TEMPLATE_MORE_INFO              3015

#define IDDI_GLOBAL_TEMPLATE_FIELD_PROPERTIES       3030
#define IDDI_GLOBAL_TEMPLATE_FIELD_DELETE           3031

#define IDDI_GLOBAL_TEMPLATE_CONTROL_IMAGES_LABEL   3101
#define IDDI_GLOBAL_TEMPLATE_CONTROL_IMAGES         3102
#define IDDI_GLOBAL_TEMPLATE_OPTIONS_GROUP          3103

#define IDDI_GLOBALTEMPLATE_CONTROL_REPARENT_FIRST         3104

#define IDDI_GLOBAL_TEMPLATE_SIGNATURE_AREA_MODE_RP        3104
#define IDDI_GLOBAL_TEMPLATE_DATE_AREA_MODE_RP             3105

#define IDDI_GLOBAL_TEMPLATE_SIGNATURE_AREAS_LABEL_RP      3106
#define IDDI_GLOBAL_TEMPLATE_SIGNATURE_AREAS_RP            3107
#define IDDI_GLOBAL_TEMPLATE_SIGNATURE_AREA_PROPS_RP       3108
#define IDDI_GLOBAL_TEMPLATE_SIGNATURE_AREA_REMOVE_RP      3109

#define IDDI_GLOBAL_TEMPLATE_DATE_AREAS_LABEL_RP           3111
#define IDDI_GLOBAL_TEMPLATE_DATE_AREAS_RP                 3112
#define IDDI_GLOBAL_TEMPLATE_DATE_AREA_PROPS_RP            3113
#define IDDI_GLOBAL_TEMPLATE_DATE_AREA_REMOVE_RP           3114

#define IDDI_GLOBALTEMPLATE_CONTROL_REPARENT_LAST   IDDI_GLOBAL_TEMPLATE_DATE_AREA_REMOVE_RP

#define IDDI_GLOBAL_TEMPLATE_IMAGE_PROPERTIES       3117
#define IDDI_GLOBAL_TEMPLATE_IMAGE_INSTRUCTIONS     3118
#define IDDI_GLOBAL_TEMPLATE_IMAGE_DESCRIPTION      3119
#define IDDI_GLOBAL_TEMPLATE_IMAGE_DESCRIPTION_LOC  31191
#define IDDI_GLOBAL_TEMPLATE_IMAGE_DESCRIPTION_COMP 31192
#define IDDI_GLOBAL_TEMPLATE_IMAGE_LOCATION         3120

#define IDD_GLOBAL_TEMPLATE_SIGNATURE_FIELD_PROPS   3125
#define IDDI_GLOBAL_TEMPLATE_SIGNATURE_FIELD_DESC   3126

#define IDDI_GLOBAL_TEMPLATE_ORDER_INST             3161
#define IDDI_GLOBAL_TEMPLATE_ORDER_LISTVIEW         3162

#define IDD_GLOBAL_TEMPLATE_SIGNATURE_FIELD_RULES   3175
#define IDDI_GLOBAL_TEMPLATE_SIGNATURE_FIELD_IMAGES_LABEL   3176
#define IDDI_GLOBAL_TEMPLATE_SIGNATURE_FIELD_IMAGES         3177
#define IDDI_GLOBAL_TEMPLATE_SIGNATURE_ROOT_FIELD_IMAGES_LABEL  3178

#define IDD_GLOBAL_TEMPLATE_DATE_FIELD_RULES        3200
#define IDDI_GLOBAL_TEMPLATE_SIGNATURE_FIELDS_LABEL 3201
#define IDDI_GLOBAL_TEMPLATE_SIGNATURE_FIELDS       3202
#define IDDI_GLOBAL_TEMPLATE_DATE_FIELDS_LABEL      3203
#define IDDI_GLOBAL_TEMPLATE_DATE_FIELDS            3204

#define IDD_GLOBAL_TEMPLATE_ROOT_PROFILE            3300
#define IDDI_GLOBAL_TEMPLATE_ROOT_INSTRUCTIONS      3301

#define IDD_GLOBAL_TEMPLATE_PROFILE                 1750

#define IDS_PROPERTIES           6
#define IDS_PDF_ENABLER          8
#define IDS_PRINTING_SUPPORT     10

#define IDS_ABOUT_2              14

#define IDS_NOT_REGISTERED       19

#define IDS_PAD_NOT_CONNECTED    28


