#pragma once

#define DISPOSITION_TITLE "Save Location"

#define IDD_ICON                   1
#define IDD_ICON_PROPERTIES        2
#define IDD_ICON_SAVE_AS           3
#define IDD_ICON_LOGO              4
#define IDD_ICON_CANCEL            5
#define IDD_ICON_DOODLE            6
#define IDD_ICON_START             7
#define IDD_ICON_CREATE            8
#define IDD_ICON_HELP              9
#define IDD_ICON_ABOUT             10
#define IDD_ICON_OPEN              11
#define IDD_ICON_WEB               12
#define IDD_ICON_WEB_HOMEPAGE      13
#define IDD_ICON_WEB_TRAINING      14
#define IDD_ICON_DOODLE_II         15
#define IDD_ICON_CANCEL_DISABLED   16
#define IDD_ICON_PROPERTIES_DISABLED   17
#define IDD_ICON_FORGET            18
#define IDD_ICON_FORGET_DISABLED   19
#define IDD_ICON_UNDO              20
#define IDD_ICON_UNDO_DISABLED     21
#define IDD_ICON_SEAL              22
#define IDD_ICON_SEAL_DISABLED     23
#define IDD_ICON_REPEAT            24
#define IDD_ICON_REPEAT_DISABLED   25
#define IDD_ICON_SAVE_AS_DISABLED  26
#define IDD_ICON_DOODLE_DISABLED   27
#define IDD_ICON_QUICK_DRAW        29
#define IDD_ICON_QUICK_DRAW_WRITE  30
#define IDD_ICON_QUICK_DRAW_WRITE_DISABLED   31
#define IDD_ICON_OPEN_DISABLED     32

#define ID_ACCELERATORS            30

#define IDBITMAP_BACKGROUND         1

#define PROPERTY_PAGE_WIDTH         360
#define PROPERTY_PAGE_HEIGHT        380

#define IDD_GLOBAL_REPOSITORY       100
#define IDD_DISPOSITION_PROPERTIES  200
#define IDD_DISPOSITION_EMAIL       300
#define IDD_PRINTER_PROFILES        400
#define IDD_BACKENDS                900
#define IDD_OPTIONS                 950
#define IDD_INHERITED_DOCUMENT      960
#define IDD_DISPOSITION_MORE        1200
#define IDD_DOODLE_OPTIONS          970
#define IDD_DISPLAY_WAITING         1300
#define IDD_REGISTRATION            1000

#define IDS_UNHANDLED_SAVE_OPTIONS      951
#define IDS_WAIT_FOR_WRITING_LOCATIONS  952
#define IDS_WAIT_FOR_WRITING_LOCATIONS_STATUS  953
#define IDS_LOOKING_FOR_PROFILE         954
#define IDS_CHOOSE_DIFFERENT_PROFILE    955
#define IDS_LOADING_PROFILES            956
#define IDS_FOUND_PROFILE               957
#define IDS_DOCUMENT_SIGNED_AND_SAVED   958
#define IDS_WRITE_ADVICE                959
#define IDS_WRITE_ADVICE_TAIL           960
#define IDS_NOMINAL_NO_DOCUMENT         961
#define IDS_SIGNED_AND_SAVED_TO         962
#define IDS_NO_PROFILES_FOUND           963
#define IDS_ONE_PROFILE_FOUND           964
#define IDS_MULTIPLE_PROFILES_FOUND     965
#define IDS_MULTIPLE_PROFILES_FOUND_TAIL            966
#define IDS_CHOOSE_PROFILE_NONE_FOUND               967
#define IDS_CHOOSE_PROFILE_NONE_FOUND_TAIL          968
#define IDS_CHOOSE_PROFILE_NONE_FOUND_TAIL_TWO      969
#define IDS_CHOOSE_PROFILE_NONE_FOUND_TAIL_THREE    970
#define IDS_CHOOSE_PROFILE_NONE_FOUND_DEFINE_NEW    971
#define IDS_NO_PROFILE_FOUND_NOMINAL_OPTION         972
#define IDS_NOMINAL_WAITING_FOR_PRINT               973
#define IDS_REGISTRATION_ID_FORMAT                  974
#define IDS_REGISTRATION_NOT_REGISTERED             975

#define IDD_CURSIVISION_CONTROL_OPTIONS         1500
#define IDD_DOCUMENT_TEMPLATE                   1600
#define IDD_CURSIVISION_RECOGNITION             1700
#define IDD_SIGNING_LOCATIONS                   1800
#define IDD_SIGNING_LOCATIONS_ORDER             1850
#define IDD_DATA_FIELDS                         1900
#define IDD_DATA_FIELDS_LABEL                   1950

#define IDD_ABOUT                               2000

#define IDD_GLOBAL_TEMPLATE_MANAGER             2500
#define IDD_GLOBAL_TEMPLAGE_PROFILE_UTILIZATION 2550
#define IDD_GLOBAL_TEMPLATE_IMAGE_MANAGER       2600

#define IDD_GLOBAL_TEMPLATE                     3000
#define IDD_GLOBAL_TEMPLATE_FIELD_PROPERTIES    3050
#define IDD_GLOBAL_TEMPLATE_FIELDS              3100
#define IDD_GLOBAL_TEMPLATE_PROFILE_ORDER       3160
#define IDD_GLOBAL_TEMPLATE_FIELD_ALTERNATES    3170
#define IDD_GLOBAL_TEMPLATE_FIELDS_INSPECT      3180

#define IDC_EXIT                 200
#define IDC_GETFILE              300
#define IDC_SAVE_AS              301
#define IDC_REOPEN_SOURCE        302
#define IDC_FILENAME             400
#define IDC_CONTROL_HOST         500
#define IDC_UPDATE_PDF           600
#define IDC_SELECT_REGION        700
#define IDC_SELECT_TARGET        701
#define IDC_SELECT_PIECES        702
#define IDC_SELECT_PIECE_TARGETS 703
#define IDC_CLOSE_FILE           704
#define IDC_CLOSE_FILE_AND_WAIT_FOR_PRINT_JOB   705
#define IDC_PRINT                706
#define IDC_SELECT_FONT          707
#define IDC_WRITE_UNCOMPRESSED   708
#define IDC_REMOVE_PAGE          709
#define IDC_REMOVE_OTHER_PAGES   710
#define IDC_REMOVE_PAGES_BEFORE  711
#define IDC_REMOVE_PAGES_AFTER   712
#define IDC_FIND_AND_APPLY_PROFILE   713

#define IDR_MAIN_MENU            100

#define ID_FILE_EXIT             160
#define ID_SIGNATURE_DEVICE      200

#define ID_CURSIVISION_ONLINE                       1306
#define ID_CURSIVISION_ONLINE_HOME                  1307
#define ID_CURSIVISION_ONLINE_TRAINING_VIDEOS       1308
#define ID_ABOUT                                    1309

#define ID_DOODLE                180
#define ID_DOODLE_CANCEL         1801
#define ID_DOODLE_OPTIONS        181
#define ID_DOODLE_FORGET         182

#define ID_SETUP                 190
#define ID_DOODLE_START          191
#define ID_RESET_DOODLE_OPTIONS  192
#define ID_MANAGE_PROFILES       193

#define ID_CANCEL_PROFILE_SEEK      201
#define ID_SELECT_PROFILE           202
#define ID_SELECTED_PROFILE_START   203

#define ID_UTILIZE_PROFILES         211

#define ID_BACKEND_EXECUTE_1     401
#define ID_BACKEND_EXECUTE_MAX   464

#define ID_BACKEND_PROPERTIES_1     501
#define ID_BACKEND_PROPERTIES_MAX   564

#define IDDI_GLOBAL_REPOSITORY      101
#define IDDI_GET_GLOBAL_REPOSITORY  102

#define IDDI_DISPOSITION_SAVE                            201
#define IDDI_DISPOSITION_SHOW_STARTUP_PROPERTIES_LABEL   202
#define IDDI_DISPOSITION_SHOW_STARTUP_PROPERTIES         203
#define IDDI_DISPOSITION_USE_LARGEST_VERTICAL_RES        204
#define IDDI_DISPOSITION_APPEND                          205
#define IDDI_DISPOSITION_APPEND_DATE                     206
#define IDDI_DISPOSITION_APPEND_TIME                     207
#define IDDI_DISPOSITION_SUFFIX                          209
#define IDDI_DISPOSITION_SUFFIX_LABEL                    210
#define IDDI_DISPOSITION_REPLACE                         211
#define IDDI_DISPOSITION_SEQUENCE                        212
#define IDDI_DISPOSITION_SAVE_IN_LABEL                   213
#define IDDI_DISPOSITION_SAVE_MY_DOCUMENTS               214
#define IDDI_DISPOSITION_SAVE_BY_ORIGINAL                215
#define IDDI_DISPOSITION_SAVE_IN                         216
#define IDDI_DISPOSITION_SAVE_LOCATION                   217
#define IDDI_DISPOSITION_CHOOSE_SAVE_LOCATION            218
#define IDDI_DISPOSITION_PRINT                           219
#define IDDI_DISPOSITION_PRINTER                         220
#define IDDI_DISPOSITION_SHOW_PROPERTIES                 228
#define IDDI_DISPOSITION_ACCEPT                          230

#define IDDI_DISPOSITION_POST_PROCESSING_LABEL           231
#define IDDI_DISPOSITION_RETAIN_SIGNED                   232
#define IDDI_DISPOSITION_REOPEN_ORIGINAL                 233
#define IDDI_DISPOSITION_CLOSE_DOCUMENT                  234
#define IDDI_DISPOSITION_KEEP_RUNNING_AND_AWAIT_JOB      235
#define IDDI_DISPOSITION_AWAIT_JOB_CLOSE                 236
#define IDDI_DISPOSITION_AWAIT_JOB_MINIMIZE              237
#define IDDI_DISPOSITION_EXIT                            238
#define IDDI_DISPOSITION_RESET                           239
#define IDDI_DISPOSITION_RESET_LABEL                     240

#define IDDI_DISPOSITION_ENABLER_MIN    IDDI_DISPOSITION_RETAIN_SIGNED
#define IDDI_DISPOSITION_ENABLER_MAX    IDDI_DISPOSITION_RESET_LABEL

#define IDDI_DISPOSITION_OPEN_LAST_DOCUMENT              241
#define IDDI_DISPOSITION_WHILE_SIGNING_PROPERTIES_LABEL  242
#define IDDI_DISPOSITION_WHILE_SIGNING_SHOW_PAD          243
#define IDDI_DISPOSITION_CONTINUOUS_DOODLE_LABEL         244
#define IDDI_DISPOSITION_CONTINUOUS_DOODLE_LEARN         245
#define IDDI_DISPOSITION_CONTINUOUS_DOODLE_OFF           246
#define IDDI_DISPOSITION_CONTINUOUS_DOODLE_ON            247
#define IDDI_DISPOSITION_REMEMBER                        248
#define IDDI_HEADER_TEXT                                 249
#define IDDI_HEADER_TEXT_A                               250
#define IDDI_HEADER_TEXT_B                               251
#define IDDI_DO_REMEMBER_LABEL                           252
#define IDDI_DISPOSITION_NEED_ADMIN_PRIVILEGES           253
#define IDDI_NO_TEMPLATE_LABEL                           254
#define IDDI_NO_TEMPLATE_LABEL2                          255
#define IDDI_SIGNATURE_REPLICATION_LABEL                 256
#define IDDI_SIGNATURE_REPLICATION_ALLOW                 257
#define IDDI_SIGNATURE_REPLICATION_DISALLOW              258
#define IDDI_SIGNATURE_REPLICATION_DEFAULT_YES           259

#define IDDI_DISPOSITION_MORE                            261
#define IDDI_DISPOSITION_SAVE_MONTHYEAR                  262
#define IDDI_DISPOSITION_SAVE_DAYMONTH                   263
#define IDDI_DISPOSITION_SAVE_VALIDATION                 264

#define IDDI_INHERITED_DOCUMENT_TEXT                     961
#define IDDI_INHERITED_DOCUMENT_PROPERTIES               962

#define IDDI_SIDEBAR_NO_DOCUMENT                         300
#define IDDI_SIDEBAR_STATUS                              301
#define IDDI_SIDEBAR_NAVIGATE                            302
#define IDDI_SIDEBAR_WRITE                               303
#define IDDI_SIDEBAR_ERASE                               304

#define IDDI_SIDEBAR_BEGIN                               305
#define IDDI_SIDEBAR_PREVIOUS                            306
#define IDDI_SIDEBAR_NEXT                                307
#define IDDI_SIDEBAR_CLEAR                               308
#define IDDI_SIDEBAR_END                                 309
#define IDDI_SIDEBAR_NAVIGATE_DURING_PLAYBACK            310
#define IDDI_SIDEBAR_CONTINUE_DURING_PLAYBACK            311
#define IDDI_SIDEBAR_CANCEL                              312

#define IDDI_SIDEBAR_FINISH                              320

#define IDDI_TOPBAR_NO_DOCUMENT                          400
#define IDDI_TOPBAR_STATUS                               401
#define IDDI_TOPBAR_INSTRUCTIONS                         402
#define IDDI_TOPBAR_FORGET                               403
#define IDDI_TOPBAR_LOCATION_STATUS                      404
#define IDDI_TOPBAR_REMOVE                               405

#define IDDI_DISPOSITION_MULTI_SIGN_RIGHT_MOTION         1101
#define IDDI_DISPOSITION_MULTI_SIGN_DOWN_MOTION          1102

#define IDDI_PRINTING_PROFILES                      400
#define IDDI_PROFILE_SET_GLOBAL                     401
#define IDDI_PRINTING_PROFILE_SETTINGS              402
#define IDDI_PRINTING_PROFILE_DELETE                403
#define IDDI_PRINTING_PROFILE_USE_FILENAME          404
#define IDDI_PRINTING_INSTRUCTIONS                  405
#define IDDI_SELECTED_PROFILE_INFORMATION_GB        406
#define IDDI_SELECTED_PROFILE_INFORMATION           407

#define IDSTR_PRINTING_INSTRUCTIONS_BUILTIN         4051
#define IDSTR_PRINTING_INSTRUCTIONS_BYNAME          4052
#define IDSTR_PRINTING_INSTRUCTIONS_GLOBAL_TEMPLATE 4053
#define IDSTR_SEEKING_PAGE_LOCATOR_AREAS            4054
#define IDSTR_FOUND_PAGE_LOCATOR_AREA               4055
#define IDSTR_SEEKING_COMPANION_LOCATOR_AREAS       4056
#define IDSTR_FOUND_COMPANION_LOCATOR_AREA          4057
#define IDSTR_SELECTED_PROFILE_IS_IMAGE_RECOGNITION 4058
#define IDSTR_SELECTED_PROFILE_IS_LEGACY            4059

#define IDDI_PRINTING_DEVICE_ASSOCIATE_PRC         410
#define IDDI_PRINTING_DEVICE_ASSOCIATION           411
#define IDDI_PRINTING_DEVICE_ASSOCIATION_FIND      412
#define IDDI_PRINTING_DEVICE_DOODLE_INSTRUCTIONS_1 413
#define IDDI_PRINTING_DEVICE_DOODLE_INSTRUCTIONS_2 414
#define IDDI_PRINTING_DEVICE_JUST_SIGN_LABEL       415
#define IDDI_PRINTING_DEVICE_JUST_SIGN             416
#define IDDI_PRINTING_DEVICE_MANUAL_CREATE_LABEL   417
#define IDDI_PRINTING_DEVICE_MANUAL_CREATE         418
#define IDDI_PRINTING_ALLOW_NON_ADMIN_ACCESS       419
#define IDDI_PRINTING_NO_RECOGNITION_STRATEGY      420
#define IDDI_PRINTING_PROFILE_START                421

#define IDDI_PRINTING_ALT_RECOGNIZE_SET_GLOBAL          423
#define IDDI_PRINTING_ALT_RECOGNIZE_LEGACY              424
#define IDDI_PRINTING_ALT_RECOGNIZE_GLOBAL_TEMPLATE     425
#define IDDI_PRINTING_ALT_RECOGNIZE_MANUAL_SELECT       426
#define IDDI_PRINTING_ALT_RECOGNIZE_MANUAL_SELECT_STR2  4262
#define IDDI_PRINTING_ALT_RECOGNIZE_NONE                427
#define IDDI_PRINTING_ALT_RECOGNIZE_DESCRIPTION         430

#define IDDI_SECONDARY_STRATEGY_GROUPBOX                    431
#define IDDI_SECONDARY_STRATEGY_DESCRIPTION                 432

#define IDDI_PRINTING_SCND_RECOGNIZE_LEGACY                 434
#define IDDI_PRINTING_SCND_RECOGNIZE_LEGACY_SPIN            444

#define IDDI_PRINTING_SCND_RECOGNIZE_GLOBAL_TEMPLATE        435
#define IDDI_PRINTING_SCND_RECOGNIZE_GLOBAL_TEMPLATE_SPIN   445

#define IDDI_PRINTING_SCND_RECOGNIZE_MANUAL_SELECT          436 // <-- make this 10 more than it's associated value
#define IDDI_PRINTING_SCND_RECOGNIZE_MANUAL_SELECT_SPIN     446

#define IDDI_PRINTING_DEVICE_PROFILE_OK         620
#define IDDI_PRINTING_DEVICE_PROFILE_CANCEL     621

#define IDDI_PRINTING_VIEW_PROFILE_NAME         701
#define IDDI_PRINTING_VIEW_INSTRUCTIONS         702
#define IDDI_PRINTING_VIEW_VIEW                 703
#define IDDI_PRINTING_VIEW_REGION_DELETE        704
#define IDDI_PRINTING_VIEW_OK                   705
#define IDDI_PRINTING_VIEW_CANCEL               706
#define IDDI_PRINTING_VIEW_POINT_SELECT         707
#define IDDI_PRINTING_VIEW_DRAG_SELECT          708
#define IDDI_PRINTING_VIEW_REGIONS_RESET        709

#define IDDI_BACKENDS_ALLOW_NON_ADMIN           901
#define IDDI_BACKENDS_LIST_LABEL                902
#define IDDI_BACKENDS_LIST                      903

#define IDDI_BACKENDS_USE_BACKEND               910
#define IDDI_BACKENDS_USE_BACKEND_MAX           942
#define IDDI_BACKENDS_PROPERTIES                943
#define IDDI_BACKENDS_PROPERTIES_MAX            975
#define IDDI_BACKENDS_ORDER                     976
#define IDDI_BACKENDS_ORDER_MAX                1008

#define IDDI_BACKENDS_TOP_LIST_LABEL           1010
#define IDDI_BACKENDS_TOP_LIST                 1011
#define IDDI_BACKENDS_BOTTOM_LIST_LABEL        1012
#define IDDI_BACKENDS_BOTTOM_LIST              1013
#define IDDI_BACKENDS_MOVE_TO_TOP_LIST         1014
#define IDDI_BACKENDS_REMOVE_FROM_TOP_LIST     1015

#define IDDI_OPTIONS_TEXT                       951
#define IDDI_OPTIONS_OPTION_1                   952
#define IDDI_OPTIONS_OPTION_2                   953
#define IDDI_OPTIONS_OPTION_3                   954
#define IDDI_OPTIONS_STATUS                     955

#define IDDI_DOODLE_OPTIONS_LABEL1              961
#define IDDI_DOODLE_OPTIONS_LABEL2              962
#define IDDI_DOODLE_OPTIONS_LABEL3              963
#define IDDI_DOODLE_OPTIONS_LABEL4              964
#define IDDI_DOODLE_OPTIONS_LABEL5              965
#define IDDI_DOODLE_OPTIONS_REMEMBER            966
#define IDDI_DOODLE_OPTIONS_FORGET              967
#define IDDI_DOODLE_OPTIONS_OWN_DISPOSITION     968
#define IDDI_DOODLE_OPTIONS_DISPOSITION         969
#define IDDI_DOODLE_OPTIONS_RESETBUTTON         970
#define IDDI_DOODLE_OPTIONS_LEFTBUTTON          971
#define IDDI_DOODLE_OPTIONS_MIDDLEBUTTON        972
#define IDDI_DOODLE_OPTIONS_RIGHTBUTTON         973
#define IDDI_DOODLE_OPTIONS_ERASEBUTTON         974
#define IDDI_DOODLE_OPTIONS_DESC                975
#define IDDI_DOODLE_OPTIONS_REPLICATION_LABEL   976
#define IDDI_DOODLE_OPTIONS_REPLICATE           977
#define IDDI_DOODLE_OPTIONS_REPLICATE_SET_YES   978
#define IDDI_DOODLE_OPTIONS_REPLICATE_SET_NO    979

#define IDDI_ABOUT_ICON                        1000
#define IDDI_ABOUT_SYSTEM_DESCRIPTION          1001
#define IDDI_ABOUT_VERSION_NO_DATE             1002
#define IDDI_ABOUT_SIGNATURE_PAD               1003
#define IDDI_ABOUT_THANK_YOU                   1004
#define IDDI_ABOUT_REGISTRATION_INFO           1005
#define IDDI_ABOUT_REGISTRATION_INFO_COPY      1006
#define IDDI_ABOUT_CHECK_FOR_PRF_UPDATES       1007
#define IDDI_ABOUT_CHECK_FOR_UPDATES_NO        1008
#define IDDI_ABOUT_CHECK_FOR_UPDATES_YES       1009
#define IDDI_ABOUT_CHECK_FOR_UPDATES_DONE      1010
#define IDDI_ABOUT_CHECK_FOR_VERSION_UPDATE    1011
#define IDDI_ABOUT_CHECK_FOR_VERSION_UPD_YES   1012
#define IDDI_ABOUT_CHECK_FOR_VERSION_UPD_NO    1013

#define IDDI_DISPLAY_WAITING_LABEL1            1301
#define IDDI_DISPLAY_WAITING_LABEL2            1302
#define IDDI_DISPLAY_WAITING_SHOW_LABEL        1303
#define IDDI_DISPLAY_WAITING_SHOW              1304

#define IDDI_SIGNING_LOCATIONS_LABEL1          1701
#define IDDI_SIGNING_LOCATIONS_LABEL2          1702
#define IDDI_SIGNING_LOCATIONS_LABEL3          1703
#define IDDI_SIGNING_LOCATIONS_VIEW            1710
#define IDDI_SIGNING_LOCATIONS_SCROLL          1711
#define IDDI_SIGNING_LOCATIONS_NEW             1720
#define IDDI_SIGNING_LOCATIONS_DELETE          1721
#define IDDI_SIGNING_LOCATIONS_CUT             1722
#define IDDI_SIGNING_LOCATIONS_COPY            1723
#define IDDI_SIGNING_LOCATIONS_PASTE           1724
#define IDDI_SIGNING_LOCATIONS_SET_ORDER       1725

#define IDDI_SIGNING_LOCATIONS_ORDER           1801
#define IDDI_SIGNING_LOCATIONS_ORDER_SPIN      1802
#define IDDI_SIGNING_LOCATIONS_ORDER_LABEL     1803
#define IDDI_SIGNING_LOCATIONS_ORDER_OK        1804
#define IDDI_SIGNING_LOCATIONS_ORDER_CANCEL    1805

#define IDDI_CV_CONTROL_TEMPLATE          100
#define IDDI_CV_CONTROL_TEMPLATE_GET      101
#define IDDI_CV_DOCUMENT                  102
#define IDDI_CV_DOCUMENT_SCROLL           103
#define IDDI_CV_RECOGNITION_INSTRUCTIONS  104
#define IDDI_CV_LOCATIONS_RESET           105
#define IDDI_CV_LIMIT_REACHED             106
#define IDDI_CV_LOCATIONS_INSTRUCTIONS    107
#define IDDI_CV_LOCATIONS_ADDITIONAL_INFO       108
#define IDDI_CV_LOCATIONS_FULLPAGE_INSTRUCTIONS 109
#define IDDI_CV_LOCATIONS_ALREADY_DEFINED       110
#define IDDI_CV_MORE_INFORMATION                111
#define IDDI_PROFILE_SELECTION_INSTRUCTIONS  112

#define IDDI_DATA_FIELDS_RESET          1901
#define IDDI_DATA_FIELDS_INSTRUCTIONS   1902
#define IDDI_DATA_FIELDS_DELETE         1903
#define IDDI_DATA_FIELDS_LABEL          1904
#define IDDI_DATA_FIELDS_GENERATE       1905
#define IDDI_DATA_FIELDS_GENERATE_LABEL 1906

#define IDDI_FIELDS_LABEL_LABEL         1951
#define IDDI_FIELDS_VALUE_REQUIRED      1952
#define IDDI_FIELDS_LABEL_OK            1953
#define IDDI_FIELDS_LABEL_CANCEL        1954
#define IDDI_FIELDS_SHOW_ALTERNATES     1955
#define IDDI_FIELDS_REGENERATE          1956
#define IDDI_FIELDS_INSPECT             1957

#define IDDI_IMAGE_FIELDS_TYPE              1975
#define IDDI_IMAGE_FIELD_TABS               2021

#define IDDI_IMAGE_FIELD_FIELD_GB           1925

#define IDDI_IMAGE_FIELD_DESCRIPTION        1926
#define IDDI_IMAGE_FIELD_LABEL              1927
#define IDDI_IMAGE_FIELD_LABEL_LEFT         1928
#define IDDI_IMAGE_FIELD_LEFT               1929
#define IDDI_IMAGE_FIELD_LEFT_SPIN          1930
#define IDDI_IMAGE_FIELD_LABEL_BOTTOM       1931
#define IDDI_IMAGE_FIELD_BOTTOM             1932
#define IDDI_IMAGE_FIELD_BOTTOM_SPIN        1933
#define IDDI_IMAGE_FIELD_LABEL_WIDTH        1934
#define IDDI_IMAGE_FIELD_WIDTH              1935
#define IDDI_IMAGE_FIELD_WIDTH_SPIN         1936
#define IDDI_IMAGE_FIELD_LABEL_HEIGHT       1937
#define IDDI_IMAGE_FIELD_HEIGHT             1938
#define IDDI_IMAGE_FIELD_HEIGHT_SPIN        1939

#define IDDI_IMAGE_FIELD_COMP_SIG_FIELD_GB  1976

#define IDDI_IMAGE_FIELD_SIG_DESCRIPTION    1977
#define IDDI_IMAGE_FIELD_SIG_LABEL          1978
#define IDDI_IMAGE_FIELD_SIG_LABEL_RIGHT    1979
#define IDDI_IMAGE_FIELD_SIG_RIGHT          1980
#define IDDI_IMAGE_FIELD_SIG_RIGHT_SPIN     1981
#define IDDI_IMAGE_FIELD_SIG_LABEL_UP       1982
#define IDDI_IMAGE_FIELD_SIG_UP             1983
#define IDDI_IMAGE_FIELD_SIG_UP_SPIN        1984
#define IDDI_IMAGE_FIELD_SIG_LABEL_WIDTH    1985
#define IDDI_IMAGE_FIELD_SIG_WIDTH          1986
#define IDDI_IMAGE_FIELD_SIG_WIDTH_SPIN     1987
#define IDDI_IMAGE_FIELD_SIG_LABEL_HEIGHT   1988
#define IDDI_IMAGE_FIELD_SIG_HEIGHT         1989
#define IDDI_IMAGE_FIELD_SIG_HEIGHT_SPIN    1990
#define IDDI_IMAGE_FIELD_SIG_NOTIFY_LABEL   1991
#define IDDI_IMAGE_FIELD_SIG_NOTIFICATION   1992
#define IDDI_IMAGE_FIELD_SIG_SIGNER_LABEL   1993
#define IDDI_IMAGE_FIELD_SIG_SIGNER_TYPE    1994
#define IDDI_IMAGE_FIELD_SIG_SIGNER_NOTE    1995
#define IDDI_IMAGE_FIELD_SIG_USE_DEFAULT_SIZE   1996
#define IDDI_IMAGE_FIELD_SIG_DEFAULT_SIZE_APPLY 1997

#define IDDI_IMAGE_FIELD_COMP_DATE_FIELD_GB 2000

#define IDDI_IMAGE_FIELD_DATE_DESCRIPTION   2001
#define IDDI_IMAGE_FIELD_DATE_LABEL         2002
#define IDDI_IMAGE_FIELD_DATE_LABEL_RIGHT   2003
#define IDDI_IMAGE_FIELD_DATE_RIGHT         2004
#define IDDI_IMAGE_FIELD_DATE_RIGHT_SPIN    2005
#define IDDI_IMAGE_FIELD_DATE_LABEL_UP      2006
#define IDDI_IMAGE_FIELD_DATE_UP            2007
#define IDDI_IMAGE_FIELD_DATE_UP_SPIN       2008
#define IDDI_IMAGE_FIELD_DATE_LABEL_WIDTH   2009
#define IDDI_IMAGE_FIELD_DATE_WIDTH         2010
#define IDDI_IMAGE_FIELD_DATE_WIDTH_SPIN    2011
#define IDDI_IMAGE_FIELD_DATE_LABEL_HEIGHT  2012
#define IDDI_IMAGE_FIELD_DATE_HEIGHT        2013
#define IDDI_IMAGE_FIELD_DATE_HEIGHT_SPIN   2014

#define IDDI_IMAGE_FIELD_PAGE_FINDER_FIELD_GB       2030
#define IDDI_IMAGE_FIELD_PAGE_FINDER_DESC           2031
#define IDDI_IMAGE_FIELD_PAGE_FINDER_SELECT_ALL     2032
#define IDDI_IMAGE_FIELD_PAGE_FINDER_SELECT_NONE    2033
#define IDDI_IMAGE_FIELD_PAGE_FINDER_LIST           2034

#define IDDI_IMAGE_FIELD_COMP_QUADRANT_GB       2050
#define IDDI_IMAGE_FIELD_COMP_QUADRANT_DESC     2051
#define IDDI_IMAGE_FIELD_COMP_QUADRANT          2052
#define IDDI_IMAGE_FIELD_COMP_ISPOSITIONAL      2053
#define IDDI_IMAGE_FIELD_COMP_QUADRANT_WIDEN    2054
#define IDDI_IMAGE_FIELD_COMP_QUADRANT_WARN     2055
#define IDDI_IMAGE_FIELD_COMP_QUADRANT_WARN2    2056
#define IDDI_IMAGE_FIELD_COMP_QUADRANT_WARN3    2057
#define IDDI_IMAGE_FIELD_COMP_QUADRANT_WARN4    2058
#define IDDI_IMAGE_FIELD_COMP_QUADRANT_WARN5    2059
#define IDDI_IMAGE_FIELD_COMP_QUADRANT_WARN6    2060

#define IDDI_IMAGE_FIELD_PROFILE_FILTER_GB          2065
#define IDDI_IMAGE_FIELD_PROFILE_FILTER_DESC        2066
#define IDDI_IMAGE_FIELD_PROF_FILTER_SELECT_ALL     2067
#define IDDI_IMAGE_FIELD_PROF_FILTER_SELECT_NONE    2068
#define IDDI_IMAGE_FIELD_PROFILE_FILTER_WARN        2069
#define IDDI_IMAGE_FIELD_PROFILE_FILTER_LIST        2070

#define IDDI_IMAGE_FIELD_ALTERNATES_INST            2075
#define IDDI_IMAGE_FIELD_ALTERNATES_OS_INST         2076
#define IDDI_IMAGE_FIELD_ALTERNATES_TF_INST         2077
#define IDDI_IMAGE_FIELD_ALTERNATES_DISP_PANE       2078
#define IDDI_IMAGE_FIELD_ALTERNATES_OS_DISP_PANE    2079
#define IDDI_IMAGE_FIELD_ALTERNATES_TF_DISP_PANE    2080
#define IDDI_IMAGE_FIELD_ALTERNATES_HSCROLL         2081
#define IDDI_IMAGE_FIELD_ALTERNATES_VSCROLL         2082
#define IDDI_IMAGE_FIELD_ALTERNATES_INFO            2083

#define IDDI_IMAGE_FIELD_INSPECTION_OUTPUT      2090
#define IDDI_IMAGE_FIELD_INSPECTION_FILE1       2091
#define IDDI_IMAGE_FIELD_INSPECTION_FILE2       2092
#define IDDI_IMAGE_FIELD_INSPECTION_FILE3       2093
#define IDDI_IMAGE_FIELD_INSPECTION_PAGENUMBER  2094
#define IDDI_IMAGE_FIELD_INSPECTION_ALTINDEX    2095

#define IDDI_IMAGE_FIELD_TEXT_FINDER_GB         2100
#define IDDI_IMAGE_FIELD_TEXT_FINDER_DESC       2101
#define IDDI_IMAGE_FIELD_TEXT_FINDER_RECT       2102
#define IDDI_IMAGE_FIELD_TEXT_FINDER_TEXT       2103
#define IDDI_IMAGE_FIELD_TEXT_FINDER_CLEAR      2104
#define IDDI_IMAGE_FIELD_TEXT_FORCE_IMAGE_MATCH 2105

#define IDDI_REGISTRATION_CV_IMAGE       1001
#define IDDI_REGISTRATION_LABEL1         1002
#define IDDI_REGISTRATION_LABEL2         1003
#define IDDI_REGISTRATION_LABEL3         10041
#define IDDI_REGISTRATION_LABEL4         1005
#define IDDI_REGISTRATION_LABEL5         1006
#define IDDI_REGISTRATION_LABEL6         1007
#define IDDI_REGISTRATION_LABEL7         1008
#define IDDI_REGISTRATION_CONTACT        1021
#define IDDI_REGISTRATION_ORGANIZATION   1022
#define IDDI_REGISTRATION_PHONE          1023
#define IDDI_REGISTRATION_EMAIL          1024
#define IDDI_REGISTRATION_RESET          1030
#define IDDI_REGISTRATION_INFO           1040
#define IDDI_REGISTRATION_INFO_OTHER_MACHINE    1041

#define IDDI_GT_MANAGER_BUNDLE_LIST_LABEL   2510
#define IDDI_GT_MANAGER_BUNDLE_LIST         2511
#define IDDI_GT_MANAGER_PACKAGE_LIST_LABEL  2512
#define IDDI_GT_MANAGER_PACKAGE_LIST        2513
#define IDDI_GT_MANAGER_ALL_PACKAGES        2514
#define IDDI_GT_MANAGER_NO_PACKAGES         2515
#define IDDI_GT_MANAGER_STAGE_PACKAGES      2516
#define IDDI_GT_MANAGER_PROFILE_RESET_LABEL 2517
#define IDDI_GT_MANAGER_PROFILE_SETTINGS    2518
#define IDDI_GT_MANAGER_PROFILE_RESET       2519
#define IDDI_GT_MANAGER_PROFILE_RESET_WARN  2520

#define IDDI_GT_MANAGER_ALLOW_NON_ADMIN_CHANGES 2521

#define IDDI_GT_MANAGER_PROF_UTIL_INST      2551
#define IDDI_GT_MANAGER_PROF_UTIL_INST2     2552
#define IDDI_GT_MANAGER_PROF_UTIL_PROF_LIST 2553
#define IDDI_GT_MANAGER_PROF_UTIL_LABEL1    2554
#define IDDI_GT_MANAGER_PROF_UTIL_LABEL2    2555
#define IDDI_GT_MANAGER_PROF_UTIL_PROF_OTHER_LIST 2556

#define IDDI_GT_IMAGE_MANAGER_INST_SIGAREA      2601
#define IDDI_GT_IMAGE_MANAGER_SIGAREA_LABELW    2602
#define IDDI_GT_IMAGE_MANAGER_SIGAREA_WIDTH     2603
#define IDDI_GT_IMAGE_MANAGER_SIGAREA_SPINLR    2604
#define IDDI_GT_IMAGE_MANAGER_SIGAREA_LABELH    2605
#define IDDI_GT_IMAGE_MANAGER_SIGAREA_HEIGHT    2606
#define IDDI_GT_IMAGE_MANAGER_SIGAREA_SPINUP    2607
#define IDDI_GT_IMAGE_MANAGER_INST_SIGAREA_APPLY    2608
#define IDDI_GT_IMAGE_MANAGER_INST_TYPES            2609
#define IDDI_GT_IMAGE_MANAGER_SIGNER_TYPES          2610
#define IDDI_GT_IMAGE_MANAGER_SIGNER_ADD            2611

#define IDDI_GLOBAL_TEMPLATE_DOCUMENT_GET_WARN      3004
#define IDDI_GLOBAL_TEMPLATE_OCV_THRESHOLD          3005
#define IDDI_GLOBAL_TEMPLATE_PROFILES_LABEL         3006
#define IDDI_GLOBAL_TEMPLATE_PROFILES               3007
#define IDDI_GLOBAL_TEMPLATE_PROFILE_ADD            3008
#define IDDI_GLOBAL_TEMPLATE_PROFILE_REMOVE         3009
#define IDDI_GLOBAL_TEMPLATE_SETTINGS               3010
#define IDDI_GLOBAL_TEMPLATE_STAGE_FOR_UPDATE       3011
#define IDDI_GLOBAL_TEMPLATE_OCV_THRESHOLD_LBL1     3014
#define IDDI_GLOBAL_TEMPLATE_OCV_BEST_STRATEGY      3015
#define IDDI_GLOBAL_TEMPLATE_TEST_PROFILE           3016

#define IDDI_GLOBAL_TEMPLATE_MORE_DOCUMENTS         3017
#define IDDI_GLOBAL_TEMPLATE_MORE_ADD               3018
#define IDDI_GLOBAL_TEMPLATE_MORE_REMOVE            3019
#define IDDI_GLOBAL_TEMPLATE_FIELDS_SHOW            3020
#define IDDI_GLOBAL_TEMPLATE_MORE_INFO              3021
#define IDDI_GLOBAL_TEMPLATE_EVEN_MORE_INFO         3022

#define IDDI_GLOBAL_TEMPLATE_FIELD_PROPERTIES       3030
#define IDDI_GLOBAL_TEMPLATE_FIELD_DELETE           3031

#define IDDI_GLOBAL_TEMPLATE_CONTROL_IMAGES_LABEL   3101
#define IDDI_GLOBAL_TEMPLATE_CONTROL_IMAGES         3102
#define IDDI_GLOBAL_TEMPLATE_OPTIONS_GROUP          3103

#define IDDI_GLOBAL_TEMPLATE_IMAGE_PROPERTIES       3117
#define IDDI_GLOBAL_TEMPLATE_IMAGE_DESCRIPTION      3118
#define IDDI_GLOBAL_TEMPLATE_IMAGE_REMOVE           3119
#define IDDI_GLOBAL_TEMPLATE_IMAGE_DESCRIPTION_FINDER               31191
#define IDDI_GLOBAL_TEMPLATE_IMAGE_DESCRIPTION_SELECTOR             31192
#define IDDI_GLOBAL_TEMPLATE_IMAGE_DESCRIPTION_COMPANION_SELECTOR   31193
#define IDDI_GLOBAL_TEMPLATE_IMAGE_DESCRIPTION_COMPANION_OPTIONAL   31194
#define IDDI_GLOBAL_TEMPLATE_IMAGE_DESCRIPTION_PAGE_LOCATOR         31195
#define IDDI_GLOBAL_TEMPLATE_IMAGE_LOCATION         3120

#define IDDI_GLOBAL_TEMPLATE_SELECTOR_FIELD_IMAGES_LABEL            3176
#define IDDI_GLOBAL_TEMPLATE_SELECTOR_FIELD_IMAGES                  3177
#define IDDI_GLOBAL_TEMPLATE_OPTIONAL_SELECTOR_FIELD_IMAGES_LABEL   3178
#define IDDI_GLOBAL_TEMPLATE_OPTIONAL_SELECTOR_FIELD_IMAGES         3179
#define IDDI_GLOBAL_TEMPLATE_PAGE_FINDER_FIELD_IMAGES_LABEL         3180
#define IDDI_GLOBAL_TEMPLATE_PAGE_FINDER_FIELD_IMAGES               3181
#define IDDI_GLOBAL_TEMPLATE_SIGNATURE_ROOT_FIELD_IMAGES_LABEL      3182

#define IDD_GLOBAL_TEMPLATE_DATE_FIELD_RULES                    3200

#define IDD_GLOBAL_TEMPLATE_ROOT_PROFILE            3300
#define IDDI_GLOBAL_TEMPLATE_ROOT_INSTRUCTIONS      3301

#define IDD_GLOBAL_TEMPLATE_PROFILE                 1750

#define IDS_PROPERTIES           6
#define IDS_PDF_ENABLER          8
#define IDS_PRINTING_SUPPORT     10
#define IDS_CANT_CREATE_FILE     11
#define IDS_CHANGE_PAD_ADMIN     12
#define IDS_CHANGE_PAD_ADMIN_2   13
#define IDS_NO_PAD               14
#define IDS_CURSIVISION_NAME     15
#define IDS_CURSIVISION_PRINTING 16
#define IDS_WELCOME_PAGE         17
#define IDS_PRINTDRIVER_NAME     18
#define IDS_REGISTRATION_PRODUCT 19

#define IDS_ABOUT_2              24

#define IDS_NOT_REGISTERED       25

#define IDS_PAD_NOT_CONNECTED    28


