
#define IDDI_PAD_MODEL_MIN             810

#define IDDI_PAD_MODEL_PHABLET         810
#define IDDI_PAD_MODEL_WACOM_LCD       811
#define IDDI_PAD_MODEL_SIGNOTEC        812
#define IDDI_PAD_MODEL_SCRIPTEL        813
#define IDDI_PAD_MODEL_TABLETPC        814

#define IDDI_PAD_MODEL_CHOICE_LABEL1   830
#define IDDI_PAD_MODEL_CHOICE_LABEL2   831
#define IDDI_PAD_MODEL_CHOICE_NONADMIN 832

#define IDDI_PAD_MODEL_MAX             814
