#define CV_VERSION_MAJOR 5
#define CV_VERSION_MINOR 1
#define CV_VERSION_REVISION 1
#define CV_VERSION_BUILD 2
#define CV_PRODUCT_VERSION "5.1.1.2"
#define VINFO(ft)           \
VS_VERSION_INFO VERSIONINFO \
FILEVERSION CV_VERSION_MAJOR,CV_VERSION_MINOR,CV_VERSION_REVISION,CV_VERSION_BUILD \
FILEFLAGSMASK 0x3fL         \
FILEFLAGS 0x0L              \
FILEOS VOS_NT_WINDOWS32     \
FILETYPE ft                 \
FILESUBTYPE 0x0              
