
#define WM_USER_MIN                 (WM_USER + 101)
#define WM_FINISH_SIGNATURE_PLAY    (WM_USER + 101)
#define WM_IMMEDIATE_DOODLE         (WM_USER + 107)
#define WM_OPEN_PDF_FILE            (WM_USER + 108)
#define WM_START_PRINT_PROCESSING   (WM_USER + 111)
#define WM_START_ADHOC              (WM_USER + 112)
#define WM_SET_ACTIVE               (WM_USER + 113)
#define WM_POTENTIAL_QUIT           (WM_USER + 114)
#define WM_FINISH_SIGNATURE_PAGE    (WM_USER + 115)
#define WM_FINISH_SIGNATURE_PAGE_2  (WM_USER + 116)
#define WM_PRINT_ONLY               (WM_USER + 117)
#define WM_CONTINUE_PLAY            (WM_USER + 118)
#define WM_PREPARE_SIGNATURE_REPLAY (WM_USER + 119)
#define WM_PLAY_NEXT_PAGE           (WM_USER + 120)
#define WM_CAN_PAD_GET_SIG_DATA     (WM_USER + 121)
#define WM_POST_PAINT               (WM_USER + 122)
#define WM_REGISTER_PAD             (WM_USER + 123)
#define WM_DISPLAY_SIGNATURE_BOX    (WM_USER + 124)
#define WM_APPLY_SIGNATURE          (WM_USER + 125)
#define WM_FIRE_DOCUMENT_OPENED     (WM_USER + 126)
#define WM_FIRE_DOCUMENT_CLOSED     (WM_USER + 127)
#define WM_FORCE_SHUTDOWN           (WM_USER + 128)
#define WM_DOCUMENT_IS_OPENED       (WM_USER + 129)
#define WM_DOCUMENT_IS_TRACKED      (WM_USER + 130)
#define WM_DOCUMENT_SET_URL         (WM_USER + 131)
#define WM_REFRESH_SIGNATURE_BOX    (WM_USER + 132)
#define WM_RESUME_PRINT_PROCESSING  (WM_USER + 133)
#define WM_REFRESH_TEMPLATE_DOC     (WM_USER + 134)
#define WM_CLEAR_TEMPLATE_DOC_VIEW  (WM_USER + 135)

#define WM_COMMAND_GLOBAL_TEMPLATE_CREATE_DOCS          WM_USER + 201
#define WM_COMMAND_SETUP_GLOBAL_TEMPLATE_PROPERTIES     WM_USER + 203
#define WM_COMMAND_ADD_IMAGE                            WM_USER + 204
#define WM_QUERY_GET_NEXT_ID                            WM_USER + 205
#define WM_COMMAND_SELECT_IMAGE                         WM_USER + 206
#define WM_COMMAND_SET_TAB_TEXT                         WM_USER + 207
#define WM_COMMAND_CREATE_TEMPLATE_UI                   WM_USER + 209
#define WM_COMMAND_GET_WINDOW_INFO                      WM_USER + 210

#define WM_COMMAND_GLOBAL_TEMPLATE_ACTIVATE_DOCS        WM_USER + 214
#define WM_COMMAND_GLOBAL_TEMPLATE_CREATE_DOCS_PART2    WM_USER + 215
#define WM_UPDATE_PDF_RECT                              WM_USER + 216
#define WM_MOUSE_DOWN_YOUR_RECT                         WM_USER + 217
#define WM_MOUSE_MOVE_YOUR_RECT                         WM_USER + 218
#define WM_CREATE_PDF_RECT                              WM_USER + 219
#define WM_QUERY_COLOR                                  WM_USER + 220
#define WM_INITIALIZE_NEW_PDF_RECT                      WM_USER + 221
#define WM_NEW_PDF_RECT                                 WM_USER + 222
#define WM_COMMAND_REPLACE_IMAGE                        WM_USER + 223
#define WM_COMMAND_CLEAR_FIELD_OUTLINES                 WM_USER + 224
#define WM_COMMAND_REDRAW_FIELD_OUTLINES                WM_USER + 225
#define WM_COMMAND_CLEAR_ONE_FIELD_OUTLINE              WM_USER + 226
#define WM_COMMAND_GLOBAL_TEMPLATE_SET_TAB_PAGE         WM_USER + 227
#define WM_COMMAND_GLOBAL_TEMPLATE_GET_TEMPLATE_UI          WM_USER + 228
#define WM_COMMAND_GLOBAL_TEMPLATE_GET_TEMPLATE_UI_INDEX    WM_USER + 229
#define WM_SET_TB_STATUS                                    WM_USER + 230
#define WM_COMMAND_GLOBAL_TEMPLATE_SYNC_RECTS_AND_BITMAPS   WM_USER + 231
#define WM_SET_TEXT_FINDER_RECT                             WM_USER + 232
#define WM_SET_TEXT_FINDER_INDEXES                          WM_USER + 233
#define WM_CLEAR_TEXT_FINDER_RECT                           WM_USER + 234
#define WM_SEE_MOUSE_DOWN                                   WM_USER + 235
#define WM_SIGNING_CONTROL_SETUP_REPLICATION                WM_USER + 236
#define WM_SIGNING_CONTROL_SET_DESCRIPTION                  WM_USER + 237

#define WM_USER_MAX                                     WM_USER + 237
